name: flucreator
description: A sample command-line application for flutter project create with getx
version: 1.0.3

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  process_run: ^0.12.2+2

executables:
  flucreator: flucreator

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
