name: flucreator
description: A sample command-line application for flutter project create with getx
version: 2.0.6
homepage: https://github.com/Abdusin/Flucreator
repository: https://github.com/Abdusin/Flucreator

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  process_run: ^0.12.2+2
  change_case: ^1.0.1
  code_builder: ^4.1.0
  dart_style: ^2.2.1

executables:
  flucreator: flucreator

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
